version: '2'

services:
  db:
    image: mysql:5.7.17
    command: --sql-mode="TRADITIONAL"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../tmp-db:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    environment:
      - DB_HOST=db
    build: .
    volumes:
      - "./app:/src/app"
    ports:
      - "3000:3000"
    command: node /var/www/docker-node-js/
    depends_on:
      - db
